"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/f2UWcyltA8r
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { Label } from "~/components/ui/label";
import { Input } from "~/components/ui/input";
import { Textarea } from "~/components/ui/textarea";
import { Button } from "~/components/ui/button";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { supportSchema } from "~/lib/validators/support";
import { Form } from "../ui/form";
import { useAction } from "next-safe-action/hooks";
import { sendSupportMessage } from "~/actions/sendSupportMessage";
import { type z } from "zod";
import { toast } from "../ui/use-toast";

export function Support() {
  const resolver = zodResolver(supportSchema);
  const form = useForm({
    resolver,
    defaultValues: {
      name: "",
      email: "",
      message: "",
    },
  });
  const { execute, result } = useAction(sendSupportMessage);

  function onSubmit(data: z.infer<typeof supportSchema>) {
    execute(data);
    if (result.data?.success) {
      toast({
        title: "Success",
        description: result.data.success,
      });
    }

    if (result.data?.failure) {
      toast({
        title: "Error",
        description: result.data.failure,
        variant: "destructive",
      });
    }
  }
  return (
    <div key="1" className="grid gap-12 md:grid-cols-2">
      <div className="space-y-4">
        <div className="space-y-2">
          <h1 className="text-4xl font-bold tracking-tight">Get in Touch</h1>
          <p className="text-gray-500 dark:text-gray-400">
            Drop us a message and we'll reach out to you promptly.
          </p>
        </div>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)}>
            <div className="space-y-4">
              <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
                <div className="space-y-2">
                  <Label className="font-medium" htmlFor="name">
                    Your Name
                  </Label>
                  <Input id="name" placeholder="Enter your name" />
                </div>
                <div className="space-y-2">
                  <Label className="font-medium" htmlFor="email">
                    Email Address
                  </Label>
                  <Input
                    id="email"
                    placeholder="Enter your email"
                    type="email"
                  />
                </div>
              </div>
              <div className="space-y-2">
                <Label className="font-medium" htmlFor="message">
                  Your Message
                </Label>
                <Textarea
                  className="min-h-[100px]"
                  id="message"
                  placeholder="Enter your message"
                />
              </div>

              <Button className="w-full">Send Message</Button>
            </div>
          </form>
        </Form>
      </div>
      <div className="space-y-4">
        <h2 className="text-3xl font-bold tracking-tight">Contact Details</h2>
        <div className="space-y-2">
          <p className="font-medium">Email</p>
          <a href="mailto:kushad.chakraborty@gmail.com">
            kushad.chakraborty@gmail.com
          </a>
        </div>
        <div className="space-y-2">
          <p className="font-medium">Phone</p>
          <a href="tel:+916289606122">+91-62896 06122</a>
        </div>
        <div className="space-y-2">
          <p className="font-medium">Address</p>
          <p>DA-105, Street-255, Action Area-1D, Newtown, Kolkata-700156</p>
        </div>
      </div>
    </div>
  );
}
