/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/NzfaUPCAkvi
 */
import Link from "next/link";
import { type JSX, type SVGProps } from "react";
import { buttonVariants } from "~/components/ui/button";
import { Card } from "~/components/ui/card";

export function Pricing() {
  return (
    <Card className="flex min-h-screen flex-col items-center justify-center bg-gray-100 dark:bg-gray-800">
      <main className="mx-auto w-full max-w-2xl px-4 py-12 sm:px-6 lg:px-8 lg:py-16">
        <div className="text-center">
          <h2 className="text-base font-semibold uppercase tracking-wide">
            Pricing
          </h2>
          <p className="mt-2 text-3xl font-extrabold text-gray-900 dark:text-gray-100 sm:text-4xl">
            One Plan for All Your Needs
          </p>
          <p className="mt-2 text-xl text-gray-500 dark:text-gray-400">
            Get unlimited access to all features at one price
          </p>
        </div>
        <div className="mt-10">
          <ul className="space-y-4 sm:space-y-0 sm:divide-y sm:divide-gray-200 sm:border-t sm:border-gray-200 lg:space-y-4">
            <li className="flex flex-col divide-y divide-gray-200 rounded-lg border shadow-sm md:flex-row md:divide-x md:divide-y-0">
              <div className="flex flex-1 flex-col p-8">
                <h3 className="text-xl font-semibold text-gray-900 dark:text-gray-100">
                  Unlimited Plan
                </h3>
                <p className="mt-4 flex-1 text-gray-500 dark:text-gray-400">
                  Unlimited access to all features for a single price.
                </p>
                <div className="mt-6">
                  <ul className="space-y-4">
                    <li className="flex items-start">
                      <div className="flex-shrink-0">
                        <CheckIcon className="h-6 w-6 text-green-500" />
                      </div>
                      <p className="ml-3 text-gray-700 dark:text-gray-300">
                        Unlimited society creation
                      </p>
                    </li>
                    <li className="flex items-start">
                      <div className="flex-shrink-0">
                        <CheckIcon className="h-6 w-6 text-green-500" />
                      </div>
                      <p className="ml-3 text-gray-700 dark:text-gray-300">
                        Unlimited roles
                      </p>
                    </li>
                    <li className="flex items-start">
                      <div className="flex-shrink-0">
                        <CheckIcon className="h-6 w-6 text-green-500" />
                      </div>
                      <p className="ml-3 text-gray-700 dark:text-gray-300">
                        Unlimited members
                      </p>
                    </li>
                    <li className="flex items-start">
                      <div className="flex-shrink-0">
                        <CheckIcon className="h-6 w-6 text-green-500" />
                      </div>
                      <p className="ml-3 text-gray-700 dark:text-gray-300">
                        Accounts management
                      </p>
                    </li>
                    <li className="flex items-start">
                      <div className="flex-shrink-0">
                        <CheckIcon className="h-6 w-6 text-green-500" />
                      </div>
                      <p className="ml-3 text-gray-700 dark:text-gray-300">
                        Unlimited roadmaps
                      </p>
                    </li>
                  </ul>
                </div>
              </div>
              <div className="flex flex-1 flex-col border-t border-gray-200 p-8 dark:border-gray-700 md:border-0 md:border-l">
                <div className="flex-1">
                  <p className="text-3xl font-semibold text-gray-900 dark:text-gray-100 sm:text-4xl">
                    <span className="mr-1">₹</span>
                    250
                  </p>
                  <p className="text-base font-semibold text-gray-500 dark:text-gray-400">
                    per month
                  </p>
                </div>
                <div className="mt-6">
                  <Link
                    className={buttonVariants({
                      className:
                        "flex w-full items-center justify-center rounded-md border border-transparent px-5 py-3 text-base font-medium",
                    })}
                    href="/auth"
                  >
                    Get started
                  </Link>
                </div>
              </div>
            </li>
          </ul>
        </div>
      </main>
    </Card>
  );
}

function CheckIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="20 6 9 17 4 12" />
    </svg>
  );
}
