/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/rtVKGJmzHYJ
 */
import { CardHeader, CardContent, Card } from "~/components/ui/card";
import Link from "next/link";
import { type JSX, type SVGProps } from "react";
import { buttonVariants } from "../ui/button";

export function Pricing() {
  return (
    <div className="flex min-h-screen flex-col items-center justify-center bg-background dark:bg-background">
      <main className="mx-auto w-full max-w-2xl px-4 py-12 sm:px-6 lg:px-8 lg:py-16">
        <div className="text-center">
          <h2 className="text-base font-semibold uppercase tracking-wide text-primary">
            Pricing
          </h2>
          <p className="mt-2 text-3xl font-extrabold text-foreground dark:text-foreground sm:text-4xl">
            One Plan for All Your Needs
          </p>
          <p className="mt-2 text-xl text-[var(--muted)] dark:text-[var(--muted-foreground)]">
            Get unlimited access to all features at one price
          </p>
        </div>
        <div className="mt-10">
          <ul className="space-y-4 sm:space-y-0 sm:divide-y sm:divide-border sm:border-t sm:border-border lg:space-y-4">
            <li className="flex flex-col divide-y divide-border rounded-lg border shadow-sm md:flex-row md:divide-x md:divide-y-0">
              <Card className="flex flex-1 flex-col bg-[var(--card)] p-8 dark:bg-[var(--card)]">
                <CardHeader>
                  <h3 className="text-xl font-semibold text-card-foreground dark:text-card-foreground">
                    Standard Plan
                  </h3>
                </CardHeader>
                <CardContent>
                  <p className="mt-4 flex-1 text-[var(--muted)] dark:text-[var(--muted-foreground)]">
                    Unlimited access to all features for a single price.
                  </p>
                  <div className="mt-6">
                    <ul className="space-y-4">
                      <li className="flex items-start">
                        <div className="flex-shrink-0">
                          <CheckIcon className="h-6 w-6 text-primary" />
                        </div>
                        <p className="ml-3 text-card-foreground dark:text-card-foreground">
                          Unlimited society creation
                        </p>
                      </li>
                      <li className="flex items-start">
                        <div className="flex-shrink-0">
                          <CheckIcon className="h-6 w-6 text-primary" />
                        </div>
                        <p className="ml-3 text-card-foreground dark:text-card-foreground">
                          Unlimited roles
                        </p>
                      </li>
                      <li className="flex items-start">
                        <div className="flex-shrink-0">
                          <CheckIcon className="h-6 w-6 text-primary" />
                        </div>
                        <p className="ml-3 text-card-foreground dark:text-card-foreground">
                          Unlimited members
                        </p>
                      </li>
                      <li className="flex items-start">
                        <div className="flex-shrink-0">
                          <CheckIcon className="h-6 w-6 text-primary" />
                        </div>
                        <p className="ml-3 text-card-foreground dark:text-card-foreground">
                          Accounts management
                        </p>
                      </li>
                      <li className="flex items-start">
                        <div className="flex-shrink-0">
                          <CheckIcon className="h-6 w-6 text-primary" />
                        </div>
                        <p className="ml-3 text-card-foreground dark:text-card-foreground">
                          Unlimited roadmaps
                        </p>
                      </li>
                    </ul>
                  </div>
                </CardContent>
              </Card>
              <div className="flex flex-1 flex-col border-t border-border p-8 dark:border-border md:border-0 md:border-l">
                <div className="flex-1">
                  <p className="text-3xl font-semibold text-foreground dark:text-foreground sm:text-4xl">
                    <span className="mr-1">₹</span>
                    250
                  </p>
                  <p className="text-base font-semibold text-[var(--muted)] dark:text-[var(--muted-foreground)]">
                    per month
                  </p>
                </div>
                <div className="mt-6">
                  <Link
                    className={buttonVariants({ className: "w-full" })}
                    href="/auth"
                  >
                    Get started
                  </Link>
                </div>
              </div>
            </li>
          </ul>
        </div>
      </main>
    </div>
  );
}

function CheckIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="20 6 9 17 4 12" />
    </svg>
  );
}
