import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";
import { cn } from "~/lib/utils";
import Navbar from "~/components/navbar";
import Tab from "~/components/navbar/Tab";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Society Management System",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          inter.variable,
        )}
      >
        <div className="m-auto w-full max-w-screen-lg">
          <TRPCReactProvider cookies={cookies().toString()}>
            <Navbar />
            <div className="min-h-screen">{children}</div>
            <Tab />
          </TRPCReactProvider>
        </div>
      </body>
    </html>
  );
}
