import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";
import { cn } from "~/lib/utils";
import Navbar from "~/components/navbar";
import Tab from "~/components/navbar/Tab";
import { getUserSubscriptionPlan } from "~/actions/getUserSubscription";
import ClientOnly from "~/components/ClientOnly";
import PaymentModal from "~/components/PaymentModal";
import { Toaster } from "~/components/ui/toaster";
import { ourFileRouter } from "~/server/storage";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { NextAuthReactProvider } from "~/next-auth/react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Society Management System",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const subscription = await getUserSubscriptionPlan();
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          inter.variable,
        )}
      >
        <div className="m-auto w-full max-w-screen-lg">
          <TRPCReactProvider cookies={cookies().toString()}>
            <NextAuthReactProvider>
              <NextSSRPlugin
                /**
                 * The `extractRouterConfig` will extract **only** the route configs
                 * from the router to prevent additional information from being
                 * leaked to the client. The data passed to the client is the same
                 * as if you were to fetch `/api/uploadthing` directly.
                 */
                routerConfig={extractRouterConfig(ourFileRouter)}
              />
              {subscription.isSubscribed ? (
                <>
                  <Navbar />
                  <div className="min-h-screen">
                    <div className="px-2">{children}</div>
                  </div>
                  <Tab />
                </>
              ) : (
                <ClientOnly>
                  <PaymentModal />
                </ClientOnly>
              )}
              <Toaster />
            </NextAuthReactProvider>
          </TRPCReactProvider>
        </div>
      </body>
    </html>
  );
}
