import "~/styles/globals.css";
import "react-loading-skeleton/dist/skeleton.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";
import { cn } from "~/lib/utils";
import { Toaster } from "~/components/ui/toaster";
import { ourFileRouter } from "~/server/storage";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { NextAuthReactProvider } from "~/next-auth/react";
import { SupabaseRealtimeReactProvider } from "~/supabase-realtime/react";
import { SpeedInsights } from "@vercel/speed-insights/next";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Society Management System",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          inter.variable,
        )}
      >
        <div className="m-auto w-full max-w-screen-lg">
          <TRPCReactProvider cookies={cookies().toString()}>
            <NextAuthReactProvider>
              <SupabaseRealtimeReactProvider>
                <NextSSRPlugin
                  routerConfig={extractRouterConfig(ourFileRouter)}
                />
                {children}
                <Toaster />
                <SpeedInsights debug />
              </SupabaseRealtimeReactProvider>
            </NextAuthReactProvider>
          </TRPCReactProvider>
        </div>
      </body>
    </html>
  );
}
